package org.pexamax.acheron;

import org.pexamax.acheron.Message;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.TreeSet;

public class Conversation extends Connection implements Persistable {
    private boolean hidden;
    private String sharedSecret;
    private String user1EncSharedSecret;
    private String user2EncSharedSecret;
    private Instant lastMessageSentTimestamp;
    private String blockerID;
    private int destructTimer;

    private ArrayList<Message> messages = new ArrayList<Message>(20); // fetch 20 messages at a time

    // To keep track of all the conversations user has
    // Ordering by the latest lastMessageSentTimestamp while having conversationID
    // as a tiebreaker to avoid merging
    private static Comparator<Conversation> reverseComparator = Comparator
            .comparing((Conversation convo) -> convo.lastMessageSentTimestamp, Comparator.reverseOrder())
            .thenComparing(convo -> convo.conversationID);
    private static TreeSet<Conversation> conversations = new TreeSet<Conversation>(reverseComparator);
    private static TreeSet<Conversation> hiddenConversations = new TreeSet<Conversation>(reverseComparator);

    // For creating a new conversation
    public Conversation(String user1ID, String user2ID) {
        this.initiatorID = user1ID;
        this.receiverID = user2ID;
        this.hidden = false;
        this.initTimestamp = Instant.now();
        this.lastMessageSentTimestamp = Instant.now();
        this.sharedSecret = "autoGenerated";
        this.blockerID = null; // No blocker initially
        this.destructTimer = 0; // No destruct timer initially
        // String user1EncSharedSecret = asymEncrypt(sharedSecret,
        // User.getUserPublicKey(user1ID));
        // String user2EncSharedSecret = asymEncrypt(sharedSecret,
        // User.getUserPublicKey(user2ID));
    }

    // For retrieving data from the database
    public Conversation(
            long conversationID,
            String user1ID,
            String user2ID,
            boolean hidden,
            String user1EncSharedSecret,
            String user2EncSharedSecret,
            Instant createdTimestamp,
            Instant lastMessageSentTimestamp,
            String blockerID,
            // All of the above params are retrieved from the database
            String currentUserID, // retrieve from client
            String privateKey // retrieve from client
    ) {
        this.ID = conversationID;
        this.initiatorID = user1ID;
        this.receiverID = user2ID;
        this.hidden = hidden;
        this.initTimestamp = createdTimestamp;
        this.lastMessageSentTimestamp = lastMessageSentTimestamp;
        this.blockerID = blockerID;
        // this.sharedSecret = asymDecrypt(currentUserID.equals(user1ID) ?
        // user1EncSharedSecret : user2EncSharedSecret, privateKey);
    }

    public void retrieveMessages() {
        // Retrieve 20 messages at a time for this conversation, and put em into the
        // message ArrayList
        // and decrypt them with the shared secret
    }

    public void displayMessages() {
        // Display the messages in this conversation from the message ArrayList
    }

    public void setDestructTimer(int timer) {
        this.destructTimer = timer;
        // update the database with the new destruct timer
    }

    public int getDestructTimer() {
        return this.destructTimer;
    }

    public static void retrieveConversations() {
        // Retrieve 10 conversations at a time based on the userID
        // Then add them to their respective collection whether they are hidden or not
    }

    public static void listConversations(boolean hidden) {
        // List all visible/hidden conversations for the user
    }

    public static void selectConversation(int index, boolean hidden) {
        // Select the conversation at the specified index
        // Display the messages in the conversation
    }

    @Override
    public void load() {
        // load message from the database
        // This will be called when the user selects a conversation
    }

    @Override
    public void save() {
        // Save the conversation's metadata to the database
        // This will be called when a field of a conversation object is being changed
    }
}
