package org.pexamax.acheron;

import org.pexamax.acheron.Message;

import java.time.Instant;
import java.util.Comparator;
import java.util.LinkedList;
import java.util.TreeSet;

public class Conversation extends Connection implements Persistable {
    private boolean hidden;
    private String sharedSecret;
    private String user1EncSharedSecret;
    private String user2EncSharedSecret;
    private Instant lastMessageSentTimestamp;
    private long blockerID;
    private int destructTimer;

    private LinkedList<Message> messages = new LinkedList<Message>(); // fetch 20 messages at a time

    // To keep track of all the conversations user has
    // Ordering by the latest lastMessageSentTimestamp while having conversationID
    // as a tiebreaker to avoid merging
    private static Comparator<Conversation> reverseComparator = Comparator
            .comparing((Conversation convo) -> convo.lastMessageSentTimestamp, Comparator.reverseOrder())
            .thenComparing(convo -> convo.getID());
    private static TreeSet<Conversation> conversations = new TreeSet<Conversation>(reverseComparator);
    private static TreeSet<Conversation> hiddenConversations = new TreeSet<Conversation>(reverseComparator);

    // For creating a new conversation
    public Conversation(long user1ID, long user2ID) {
        super(user1ID, user2ID);
        this.hidden = false;
        this.lastMessageSentTimestamp = Instant.now();
        this.sharedSecret = "autoGenerated";
        this.blockerID = 0; // No blocker initially
        this.destructTimer = 0; // No destruct timer initially
        // String user1EncSharedSecret = asymEncrypt(sharedSecret,
        // User.getUserPublicKey(user1ID));
        // String user2EncSharedSecret = asymEncrypt(sharedSecret,
        // User.getUserPublicKey(user2ID));
    }

    // For retrieving data from the database
    public Conversation(
            long conversationID,
            long user1ID,
            long user2ID,
            boolean hidden,
            String user1EncSharedSecret,
            String user2EncSharedSecret,
            Instant createdTimestamp,
            Instant lastMessageSentTimestamp,
            long blockerID,
            // All of the above params are retrieved from the database
            String currentUserID, // retrieve from client
            String privateKey // retrieve from client
    ) {
        super(conversationID, user1ID, user2ID, createdTimestamp);
        this.setHidden(hidden);
        this.setUser1EncSharedSecret();
        this.setUser2EncSharedSecret();
        this.setLastMessageSentTimestamp(lastMessageSentTimestamp);
        this.setBlockerID(blockerID);
        // this.sharedSecret = asymDecrypt(currentUserID.equals(user1ID) ?
        // user1EncSharedSecret : user2EncSharedSecret, privateKey);
    }

    public void retrieveMessages() {
        // If no messages are currently loaded:
        //     fetch messages from the database for the current conversation
        //     order by timestamp from newest to oldest
        // Else:
        //     fetch messages from the database for the current conversation
        //     where sent_time < oldest message's sent_time in collection
        //     order by timestamp from newest to oldest
        // Insert the fetched messages into the collection in the beginning from most to least recent

        // if (this.messages.isEmpty()) {
        //     String query = "SELECT * FROM message WHERE conversation_id = ? ORDER BY sent_time DESC LIMIT 20";
        //     PreparedStatement statement = kk
        // } else {
        //     // Fetch messages from the database for the current conversation
        //     // where sent_time < oldest message's sent_time in collection
        //     // Order by timestamp from newest to oldest
        // }
    }

    public void displayMessages() {
        for (Message message : messages) {
            System.out.println(message.toString());
        }
    }

    private void setHidden(boolean hidden) {
        if (this.hidden == hidden) return; 
        this.hidden = hidden;
    }

    private void setSharedSecret(String sharedSecret) {
        if (sharedSecret != null && !sharedSecret.isEmpty()) this.sharedSecret = sharedSecret;
        else throw new IllegalArgumentException("Shared secret cannot be null or empty");
    }

    private void setUser1EncSharedSecret() {
        if (user1EncSharedSecret != null && !user1EncSharedSecret.isEmpty()) {
            // Use User1's public key to encrypt the shared secret
            this.user1EncSharedSecret = "encryptedSharedSecretUsingUser1PublicKey";
        } else throw new IllegalArgumentException("User 1 encrypted shared secret cannot be null or empty");
    }

    private void setUser2EncSharedSecret() {
        if (user1EncSharedSecret != null && !user1EncSharedSecret.isEmpty()) {
            // Use User2's public key to encrypt the shared secret
            this.user1EncSharedSecret = "encryptedSharedSecretUsingUser2PublicKey";
        } else throw new IllegalArgumentException("User 2 encrypted shared secret cannot be null or empty");
    }

    private void setLastMessageSentTimestamp(Instant lastMessageSentTimestamp) {
        if (lastMessageSentTimestamp != null) this.lastMessageSentTimestamp = lastMessageSentTimestamp;
        else throw new IllegalArgumentException("Current timestamp cannot be null");
    }

    public void setBlockerID(long blockerID) {
        if (blockerID < 0 && blockerID != super.getInitiatorID() && blockerID != super.getReceiverID()) this.blockerID = blockerID;
        else throw new IllegalArgumentException("Blocker ID cannot be null or empty");
    }

    public void setDestructTimer(int timer) {
        int oneWeekInSeconds = 604800;
        if (timer < 0) this.destructTimer = 0; // No destruct timer
        else if (timer > oneWeekInSeconds) this.destructTimer = oneWeekInSeconds; // Max 7 days 
        // update the database with the new destruct timer
    }

    public int getDestructTimer() {
        return this.destructTimer;
    }

    public static void retrieveConversations() {
        // Retrieve 10 conversations at a time based on the userID
        // Then add them to their respective collection whether they are hidden or not
    }

    public static void listConversations(boolean hidden) {
        // List all visible/hidden conversations for the user
    }

    public static void selectConversation(int index, boolean hidden) {
        // Select the conversation at the specified index
        // Display the messages in the conversation
    }

    public static boolean areUsersConnected(long user1ID, long user2ID) {
        // Query for the connections between user1 and user2 from conversation table
        // If a connection exists the table, return true
        // else:
        return false;
    }

    @Override
    public void load() {
        // load message from the database
        // This will be called when the user selects a conversation
    }

    @Override
    public void save() {
        // Save the conversation's metadata to the database
        // This will be called when a field of a conversation object is being changed
    }

    @Override
    public String toString() {
        return super.toString() + "isHidden: " + this.hidden + "\n lastMessageSentTimestamp: " + this.lastMessageSentTimestamp + "\n blockerID: " + this.blockerID + "\n destructTimer: " + this.destructTimer + "\n";
    }

    @Override
    public boolean equals(Object convo) {
        if (convo == null || !(convo instanceof Conversation)) return false;
        return (convo instanceof Conversation) && 
            this.hidden == ((Conversation)convo).hidden && 
            this.lastMessageSentTimestamp.equals(((Conversation)convo).lastMessageSentTimestamp) &&
            this.blockerID.equals(((Conversation)convo).blockerID) &&
            this.sharedSecret.equals(((Conversation)convo).sharedSecret) &&
            this.destructTimer == ((Conversation)convo).destructTimer;
    }
    
    public boolean equals(Connection conn) {
        return super.equals(conn);
    }
}
