package org.pexamax.acheron;

import org.pexamax.acheron.Message;

import java.time.Instant;
import java.util.ArrayList;

public class Conversation {

	private long conversationID; 

	private boolean hidden;
	private String user1ID;
	private String user2ID;
	private String sharedSecret;
    private String user1EncSharedSecret;
    private String user2EncSharedSecret;
	private Instant createdTimestamp;
	private Instant lastMessageSentTimestamp;
	private String blockerID;
    private int destructTimer;
    private ArrayList<Message> messages = new ArrayList<Message>(20); // fetch 20 messages at a time

    // To keep track of all the conversations user has
    private static ArrayList<Conversation> conversations = new ArrayList<Conversation>(5); // fetch 5 conversations at a time
    private static ArrayList<Conversation> hiddenConvo = new ArrayList<Conversation>(5); // fetch 5 hidden conversations at a time

    // For creating a new conversation
	public Conversation(String user1ID, String user2ID) {
        this.user1ID = user1ID;
        this.user2ID = user2ID;
        this.hidden = false;
        this.createdTimestamp = Instant.now();
        this.lastMessageSentTimestamp = Instant.now();
        this.sharedSecret = "autoGenerated";
        this.blockerID = null; // No blocker initially
        this.destructTimer = 0; // No destruct timer initially
        // String user1EncSharedSecret = asymEncrypt(sharedSecret, User.getUserPublicKey(user1ID));
        // String user2EncSharedSecret = asymEncrypt(sharedSecret, User.getUserPublicKey(user2ID));
	}

    // For retrieving data from the database
    public Conversation (
            long conversationID, 
            String user1ID, 
            String user2ID, 
            boolean hidden,
            String user1EncSharedSecret, 
            String user2EncSharedSecret, 
            Instant createdTimestamp, 
            Instant lastMessageSentTimestamp, 
            String blockerID,
            // All of the above params are retrieved from the database
            String currentUserID, // retrieve from client
            String privateKey // retrieve from client
            ) {
        this.conversationID = conversationID;
        this.user1ID = user1ID;
        this.user2ID = user2ID;
        this.hidden = hidden;
        this.createdTimestamp = createdTimestamp;
        this.lastMessageSentTimestamp = lastMessageSentTimestamp;
        this.blockerID = blockerID;
        // this.sharedSecret = asymDecrypt(currentUserID.equals(user1ID) ? user1EncSharedSecret : user2EncSharedSecret, privateKey);
    }

    public static void retrieveConversations(String userID) {
        // Retrieve 5 conversations at a time based on the userID 
        // Then add them to their respective collection whether they are hidden or not
    }

    public static void listConversations(boolean hidden) {
        // List all visible conversations for the user
    }

    public static Conversation selectConversation(int index, boolean hidden) {
        // Get the conversation at the specified index
        return null;
    }

    public void retrieveMessages() {
        // Retrieve 20 messages at a time for this conversation, and put em into the message ArrayList
        // and decrypt them with the shared secret
    }

    public void displayMessages() {
        // Display the messages in this conversation from the message ArrayList
    }

    public void setDestructTimer(int timer) { this.destructTimer = timer; }
    public int getDestructTimer() { return this.destructTimer; }

}
